### ISSUE TITLE
New version hangs

### ISSUE THREAD

**Issue by unle70** [web2py/web2py#2507]
Hi,

I tried to download revision 3.0.8 and I see a problem. Previously I was using revision 2.27.1.
The most obvious issues are in the Administrative Interface (Admin app). It hangs all the time. 
I try to pick "edit" on my application and it doesn't open. Then I stop the browser and try clicking "edit" again, and this time it DOES open. Then, trying to edit a controller and it doesn't open. For editing files, re-trying does not help.

I tried running my application itself.
Menu items CAN open and run, but some AJAX requests get stuck and cannot complete.

I'm too scared to do the upgrade in the production environment (Using IIS) until I get to the bottom of this failure. Maybe it's all just a "rocket" issue, but I'm not sure yet.

Any ideas?

**Comment by nicozanf** [comment]
should be fixed by a simple change on rocket3, see https://github.com/web2py/rocket3/pull/5 . Can you confirm?

**Comment by unle70** [comment]
Well, it partially solved it.
I upgraded to Rev. 3.0.9, but that didn't work.
Manually implementing the modification in Rocket does allow the files to be opened for editing. But there's still some strange error message in the editor window, asking to "reload" the page. When reloading, it just shows the same error message again.
I'm still not sure if this is a problem with my environment, or a general bug.

**Comment by unle70** [comment]
Finally looks like everything is working properly.
The problem was in the local copy of "appadmin.py" (inside my application/controllers folder). After upgrading it to the latest version, problem is solved.
