### ISSUE TITLE
datetime <-> json conversion fails

### ISSUE THREAD

**Issue by macfiron** [web2py/web2py#881]
let the output speak for itself:
silvan@typhon:~/local/web2py$ ./web2py.py -S welcome
In [1]: import datetime
In [2]: test_data = { 'somedate': datetime.date(2015, 3, 30) }
In [3]: import gluon.contrib.simplejson
In [4]: gluon.contrib.simplejson.dumps(test_data)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-f2aa1271c765> in <module>()
----> 1 gluon.contrib.simplejson.dumps(test_data)

/home/silvan/local/web2py/gluon/contrib/simplejson/__init__.pyc in dumps(obj, skipkeys, ensure_ascii, check_circular, allow_nan, cls, indent, separators, encoding, default, use_decimal, **kw)
    261         encoding == 'utf-8' and default is None and not use_decimal
    262         and not kw):
--> 263         return _default_encoder.encode(obj)
    264     if cls is None:
    265         cls = JSONEncoder

/home/silvan/local/web2py/gluon/contrib/simplejson/encoder.pyc in encode(self, o)
    215         chunks = self.iterencode(o, _one_shot=True)
    216         if not isinstance(chunks, (list, tuple)):
--> 217             chunks = list(chunks)
    218         if self.ensure_ascii:
    219             return ''.join(chunks)

/home/silvan/local/web2py/gluon/contrib/simplejson/encoder.pyc in _iterencode(o, _current_indent_level)
    484                 yield chunk
    485         elif isinstance(o, dict):
--> 486             for chunk in _iterencode_dict(o, _current_indent_level):
    487                 yield chunk
    488         elif _use_decimal and isinstance(o, Decimal):

/home/silvan/local/web2py/gluon/contrib/simplejson/encoder.pyc in _iterencode_dict(dct, _current_indent_level)
    458                 else:
    459                     chunks = _iterencode(value, _current_indent_level)
--> 460                 for chunk in chunks:
    461                     yield chunk
    462         if newline_indent is not None:

/home/silvan/local/web2py/gluon/contrib/simplejson/encoder.pyc in _iterencode(o, _current_indent_level)
    494                     raise ValueError("Circular reference detected")
    495                 markers[markerid] = o
--> 496             o = _default(o)
    497             for chunk in _iterencode(o, _current_indent_level):
    498                 yield chunk

/home/silvan/local/web2py/gluon/contrib/simplejson/encoder.pyc in default(self, o)
    189 
    190         """
--> 191         raise TypeError(repr(o) + " is not JSON serializable")
    192 
    193     def encode(self, o):

TypeError: datetime.date(2015, 3, 30) is not JSON serializable

**Comment by macfiron** [comment]
Sry, writing this issue went terribly wrong somehow.
Hopefully, the report above is readable.
Forgot the following:
silvan@typhon:~/local/web2py$ ./web2py.py --version
Version 2.9.12-stable+timestamp.2015.01.17.06.11.03
and
silvan@typhon:~/local/web2py$ python --version
Python 2.7.6
running on an Ubuntu 14.04.2

**Comment by niphlod** [comment]
this should be fixed with the latest pydal

**Comment by niphlod** [comment]
if noone comments further, I'm going to close this in a few days

**Comment by macfiron** [comment]
I just downloaded the web2py source package. The above error still occurs.

Then I git cloned --recursive the web2py, entered the new web2py directory and tried the above and it gave the same error.

Either I'm doing something wrong, or the mentioned latest pydal is not part of the web2py source package or the error is not fixed.

**Comment by niphlod** [comment]
super-whoops: I thought it was related to another nifty bug that was fixed. 
Confirmed, you're doing something wrong. gluon.contrib.simplejson is nothing more than the json module you can find in python >= 2.7 . It's not doing anything fancy there, just being "supportive" for whoever is running web2py with python 2.6.

Now, small recap:
```
Python 2.7.8 (default, Oct 20 2014, 15:05:19) 
[GCC 4.9.1] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import json
>>> import datetime
>>> json.dumps({'a' : 1})
'{"a": 1}'
>>> json.dumps({'a' : datetime.date(2015,1,1)})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: datetime.date(2015, 1, 1) is not JSON serializable
>>> 
```
the json library CAN'T serialize date(time) values.
What you should use instead is 

```
>>> from gluon.serializers import json
>>> json({'a' : datetime.date(2015,1,1)})
u'{"a": "2015-01-01"}'
>>> 
```
I know, bad naming... gluon.serializers exposes "json()" not as the "original" module, but as a somewhat more intuitive "dumps()" function with higher understanding of how a date should be serialized.
I'm going to close this, feel free to add comments if you didn't understand properly.

**Comment by macfiron** [comment]
Your help is very much appreciated, thank you!

(Hopefully this won't automatically reopen the issue, I've never done this before)

**Comment by niphlod** [comment]
no worries, it's all ok. Bye!
